// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_reservoir
arma::mat run_reservoir(arma::mat inputs, arma::mat win, arma::mat wres, double alpha);
RcppExport SEXP _echos_run_reservoir(SEXP inputsSEXP, SEXP winSEXP, SEXP wresSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type win(winSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wres(wresSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(run_reservoir(inputs, win, wres, alpha));
    return rcpp_result_gen;
END_RCPP
}
// train_ridge
Rcpp::List train_ridge(const arma::mat& X, const arma::mat& y, double lambda, const arma::colvec& weights);
RcppExport SEXP _echos_train_ridge(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(train_ridge(X, y, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_echos_run_reservoir", (DL_FUNC) &_echos_run_reservoir, 4},
    {"_echos_train_ridge", (DL_FUNC) &_echos_train_ridge, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_echos(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
