# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_reservoir <- function(inputs, win, wres, alpha) {
    .Call(`_echos_run_reservoir`, inputs, win, wres, alpha)
}

train_ridge <- function(X, y, lambda, weights) {
    .Call(`_echos_train_ridge`, X, y, lambda, weights)
}

