# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name run_reservoir
#' @title Run reservoir
#' @description Run reservoir creates the internal states for the ESN.
#' 
#' @param input Numeric matrix containing the input features
#' @param win Numeric matrix. The input weight matrix.
#' @param wres Numeric matrix. The reservoir weight matrix.
#' @param alpha Numeric value. The leakage rate (smoothing parameter).
#' 
#' @return states train Numeric matrix with the internal states.
NULL

run_reservoir <- function(inputs, win, wres, alpha) {
    .Call(`_echos_run_reservoir`, inputs, win, wres, alpha)
}

#' @name train_ridge
#' @title Estimate ridge regression
#' @description Estimate coefficients via ridge regression.
#' 
#' @param X Numeric matrix. The design matrix containing the predictor variables.
#' @param y Numeric matrix. The response variable(s).
#' @param lambda Numeric value. The regularization parameter.
#' @param weights Numeric vector. Observation weights.
#' 
#' @return A list containing the estimated coefficients, fitted values, etc.
NULL

train_ridge <- function(X, y, lambda, weights) {
    .Call(`_echos_train_ridge`, X, y, lambda, weights)
}

